// Copyright (C) 2025 Dominik (Pavlicek) Morse. All rights reserved.
//
// Developed for the Mountea Framework as a free tool. This solution is provided
// for use and sharing without charge. Redistribution is allowed under the following conditions:
//
// - You may use this solution in commercial products, provided the product is not
//   this solution itself (or unless significant modifications have been made to the solution).
// - You may not resell or redistribute the original, unmodified solution.
//
// For more information, visit: https://mountea.tools

#include "K2Nodes/K2Node_SetJsonFieldByName.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "Helpers/MounteaJsonObject.h"
#include "K2Node_CallFunction.h"
#include "K2Node_IfThenElse.h"
#include "KismetCompiler.h"
#include "Statics/MounteaAdvancedInventoryJsonStatics.h"
#include "Styling/MounteaAdvancedInventoryDeveloperStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_SetJsonFieldByName"

const FName UK2Node_SetJsonFieldByName::TargetPinName(TEXT("Target"));
const FName UK2Node_SetJsonFieldByName::FieldNamePinName(TEXT("FieldName"));
const FName UK2Node_SetJsonFieldByName::ValuePinName(TEXT("Value"));
const FName UK2Node_SetJsonFieldByName::JsonObjectPinName(TEXT("JsonObject"));
const FName UK2Node_SetJsonFieldByName::FailedPinName(TEXT("Failed"));

UK2Node_SetJsonFieldByName::UK2Node_SetJsonFieldByName(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
}

void UK2Node_SetJsonFieldByName::AllocateDefaultPins()
{
	const UEdGraphSchema_K2* nodeSchema = GetDefault<UEdGraphSchema_K2>();

	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, FailedPinName);
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UMounteaJsonObject::StaticClass(), TargetPinName);

	UEdGraphPin* fieldNamePin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Name, FieldNamePinName);
	fieldNamePin->PinToolTip = LOCTEXT("K2Node_SetJsonFieldByName_FieldName", "JSON field name to set.").ToString();
	nodeSchema->SetPinAutogeneratedDefaultValueBasedOnType(fieldNamePin);

	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Wildcard, ValuePinName);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Object, UMounteaJsonObject::StaticClass(), JsonObjectPinName);
}

void UK2Node_SetJsonFieldByName::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* actionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(actionKey))
	{
		UBlueprintNodeSpawner* nodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(nodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(actionKey, nodeSpawner);
	}
}

bool UK2Node_SetJsonFieldByName::IsSupportedValuePinType(const FEdGraphPinType& PinType)
{
	if (PinType.ContainerType != EPinContainerType::None)
		return false;

	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Int ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Int64 ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Real ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Boolean ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_String ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Name ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Byte ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Text ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Struct ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Object ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_SoftObject ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Class ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_SoftClass)
	{
		return true;
	}

	return false;
}

bool UK2Node_SetJsonFieldByName::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin->PinName == ValuePinName && MyPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
	{
		if (OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec ||
			OtherPin->PinType.PinCategory == UEdGraphSchema_K2::PC_Wildcard)
		{
			OutReason = LOCTEXT("InvalidConnection", "Cannot connect to exec or wildcard pins").ToString();
			return true;
		}

		if (!IsSupportedValuePinType(OtherPin->PinType))
		{
			OutReason = LOCTEXT("UnsupportedType", "Unsupported JSON field type").ToString();
			return true;
		}
	}

	return false;
}

void UK2Node_SetJsonFieldByName::NotifyPinConnectionListChanged(UEdGraphPin* Pin)
{
	Super::NotifyPinConnectionListChanged(Pin);

	if (Pin->PinName == ValuePinName)
		RefreshPinTypes();
}

void UK2Node_SetJsonFieldByName::RefreshPinTypes() const
{
	UEdGraphPin* valuePin = FindPinChecked(ValuePinName);

	if (valuePin->LinkedTo.Num() > 0 && valuePin->LinkedTo[0])
	{
		valuePin->PinType = valuePin->LinkedTo[0]->PinType;
		valuePin->PinType.PinSubCategory = valuePin->LinkedTo[0]->PinType.PinSubCategory;
		valuePin->PinType.PinSubCategoryObject = valuePin->LinkedTo[0]->PinType.PinSubCategoryObject;
	}
	else
	{
		valuePin->PinType.PinCategory = UEdGraphSchema_K2::PC_Wildcard;
		valuePin->PinType.PinSubCategory = NAME_None;
		valuePin->PinType.PinSubCategoryObject = nullptr;
		valuePin->PinType.ContainerType = EPinContainerType::None;
		valuePin->PinType.bIsReference = false;
		valuePin->PinType.bIsConst = false;
	}

	if (UEdGraph* graph = GetGraph())
		graph->NotifyGraphChanged();
}

UFunction* UK2Node_SetJsonFieldByName::GetTargetFunction(const UEdGraphPin* ValuePin)
{
	const UClass* staticsClass = UMounteaAdvancedInventoryJsonStatics::StaticClass();

	if (!ValuePin)
		return nullptr;

	const FEdGraphPinType& effectiveType = GetEffectiveType(ValuePin);
	if (!IsSupportedValuePinType(effectiveType))
		return nullptr;

	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Int)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetIntJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Int64)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetInt64JsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Real)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetFloatJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Boolean)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetBoolJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_String)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetStringJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Name)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetNameJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Byte)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetByteJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Text)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetTextJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Object)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetObjectJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_SoftObject)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetSoftObjectJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Class)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetClassJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_SoftClass)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetSoftClassJsonField));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Struct)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetStructJsonField));

	return nullptr;
}

void UK2Node_SetJsonFieldByName::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	UEdGraphPin* execPin = GetExecPin();
	UEdGraphPin* thenPin = GetThenPin();
	UEdGraphPin* failedPin = FindPinChecked(FailedPinName);
	UEdGraphPin* targetPin = FindPinChecked(TargetPinName);
	UEdGraphPin* fieldNamePin = FindPinChecked(FieldNamePinName);
	UEdGraphPin* valuePin = FindPinChecked(ValuePinName);
	UEdGraphPin* jsonObjectPin = FindPinChecked(JsonObjectPinName);
	const UEdGraphSchema_K2* schema = CompilerContext.GetSchema();
	if (!schema)
	{
		BreakAllNodeLinks();
		return;
	}

	if (valuePin->LinkedTo.Num() == 0)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("NoValueConnected", "@@ must have Value pin connected").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	const FEdGraphPinType& effectiveType = GetEffectiveType(valuePin);
	UFunction* targetFunction = GetTargetFunction(valuePin);
	if (!targetFunction)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("UnsupportedValueType", "@@ has unsupported JSON field value type").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UK2Node_CallFunction* callFunctionNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	callFunctionNode->SetFromFunction(targetFunction);
	callFunctionNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*execPin, *callFunctionNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*targetPin, *callFunctionNode->FindPinChecked(TEXT("Target")));
	CompilerContext.MovePinLinksToIntermediate(*fieldNamePin, *callFunctionNode->FindPinChecked(TEXT("FieldName")));

	UEdGraphPin* callValuePin = callFunctionNode->FindPinChecked(TEXT("Value"));
	if (effectiveType.PinCategory == UEdGraphSchema_K2::PC_Struct)
		callValuePin->PinType = effectiveType;
	CompilerContext.MovePinLinksToIntermediate(*valuePin, *callValuePin);

	UEdGraphPin* callJsonObjectPin = callFunctionNode->FindPinChecked(JsonObjectPinName);
	CompilerContext.MovePinLinksToIntermediate(*jsonObjectPin, *callJsonObjectPin);

	UK2Node_IfThenElse* branchNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
	branchNode->AllocateDefaultPins();

	schema->TryCreateConnection(callFunctionNode->GetThenPin(), branchNode->GetExecPin());
	schema->TryCreateConnection(callFunctionNode->GetReturnValuePin(), branchNode->GetConditionPin());

	CompilerContext.MovePinLinksToIntermediate(*thenPin, *branchNode->GetThenPin());
	CompilerContext.MovePinLinksToIntermediate(*failedPin, *branchNode->GetElsePin());

	BreakAllNodeLinks();
}

void UK2Node_SetJsonFieldByName::PostReconstructNode()
{
	Super::PostReconstructNode();
	RefreshPinTypes();
}

#if WITH_EDITOR

FText UK2Node_SetJsonFieldByName::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	FText functionName = LOCTEXT("SetJsonFieldByName_Title", "JSON - Set Field by Name");

	if (TitleType == ENodeTitleType::FullTitle)
	{
		FText contextString = LOCTEXT("SetJsonFieldByName_Subtitle", "Source is Mountea Json Object");

		FFormatNamedArguments namedArgs;
		namedArgs.Add(TEXT("FunctionName"), functionName);
		namedArgs.Add(TEXT("ContextString"), contextString);

		return FText::Format(LOCTEXT("SetJsonFieldByName_Title_WithContext", "{FunctionName}\n{ContextString}"), namedArgs);
	}

	return functionName;
}

FText UK2Node_SetJsonFieldByName::GetTooltipText() const
{
	return LOCTEXT("SetJsonFieldByName_Tooltip",
		"Sets a dynamic JSON field by name on a Mountea Json Object.\n\n"
		"Supported Types:\n"
		"- Int\n"
		"- Int64\n"
		"- Float\n"
		"- Bool\n"
		"- String, Name, Text, Byte\n"
		"- Object, Soft Object, Class, Soft Class\n"
		"- Mountea Json Object as a nested JSON object\n"
		"- Any UStruct as a nested JSON object");
}

FText UK2Node_SetJsonFieldByName::GetToolTipHeading() const
{
	return LOCTEXT("SetJsonFieldByName_TooltipHeading", "Mountea Advanced Inventory Function");
}

FLinearColor UK2Node_SetJsonFieldByName::GetNodeTitleColor() const
{
	return FLinearColor(0.0f, 0.55f, 0.62f);
}

FSlateIcon UK2Node_SetJsonFieldByName::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = FLinearColor(.823f, .823f, .823f);
	return FSlateIcon(FMounteaAdvancedInventoryDeveloperStyle::GetAppStyleSetName(), "MAISStyleSet.K2Node_SetPropertyByName.Small");
}

FName UK2Node_SetJsonFieldByName::GetCornerIcon() const
{
	const FName superName = Super::GetCornerIcon();
	return superName == NAME_None ? TEXT("MAISStyleSet.MounteaLogo") : superName;
}

FText UK2Node_SetJsonFieldByName::GetMenuCategory() const
{
	return LOCTEXT("SetJsonFieldByName_Category", "Mountea|Inventory & Equipment|JSON");
}

#endif

#undef LOCTEXT_NAMESPACE
