// Copyright (C) 2025 Dominik (Pavlicek) Morse. All rights reserved.
//
// Developed for the Mountea Framework as a free tool. This solution is provided
// for use and sharing without charge. Redistribution is allowed under the following conditions:
//
// - You may use this solution in commercial products, provided the product is not
//   this solution itself (or unless significant modifications have been made to the solution).
// - You may not resell or redistribute the original, unmodified solution.
//
// For more information, visit: https://mountea.tools

#include "K2Nodes/K2Node_BreakJsonObjectByDefinition.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "Helpers/MounteaJsonObject.h"
#include "K2Node_CallFunction.h"
#include "K2Node_IfThenElse.h"
#include "KismetCompiler.h"
#include "Settings/MounteaAdvancedInventoryGlobalConfig.h"
#include "Statics/MounteaAdvancedInventoryJsonStatics.h"
#include "Styling/MounteaAdvancedInventoryDeveloperStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_BreakJsonObjectByDefinition"

const FName UK2Node_BreakJsonObjectByDefinition::JsonObjectPinName(TEXT("JsonObject"));
const FName UK2Node_BreakJsonObjectByDefinition::DefinitionKeyPinName(TEXT("DefinitionKey"));
const FName UK2Node_BreakJsonObjectByDefinition::ErrorsPinName(TEXT("Errors"));
const FName UK2Node_BreakJsonObjectByDefinition::FailedPinName(TEXT("Failed"));
const FString UK2Node_BreakJsonObjectByDefinition::FieldPinPrefix(TEXT("Field_"));

UK2Node_BreakJsonObjectByDefinition::UK2Node_BreakJsonObjectByDefinition(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	bDisableOrphanPinSaving = true;
}

void UK2Node_BreakJsonObjectByDefinition::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, FailedPinName);

	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UMounteaJsonObject::StaticClass(), JsonObjectPinName);

	UEdGraphPin* definitionKeyPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_String, DefinitionKeyPinName);
	definitionKeyPin->DefaultValue = CachedDefinitionKey.IsEmpty() ? TEXT("none") : CachedDefinitionKey;
	definitionKeyPin->AutogeneratedDefaultValue = TEXT("none");

	UEdGraphPin* errorsPin = CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_String, ErrorsPinName);
	errorsPin->PinType.ContainerType = EPinContainerType::Array;

	FMounteaJsonObjectDefinition definition;
	TArray<FString> errors;
	if (ResolveSelectedDefinition(definition, errors))
		CreateFieldPins(definition);
}

void UK2Node_BreakJsonObjectByDefinition::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* actionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(actionKey))
	{
		UBlueprintNodeSpawner* nodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(nodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(actionKey, nodeSpawner);
	}
}

bool UK2Node_BreakJsonObjectByDefinition::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin && MyPin->PinName == DefinitionKeyPinName)
	{
		OutReason = LOCTEXT("DefinitionKeyMustBeLiteral", "Definition Key must be selected from the node dropdown so field pins can be generated.").ToString();
		return true;
	}

	return false;
}

void UK2Node_BreakJsonObjectByDefinition::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin && Pin->PinName == DefinitionKeyPinName)
	{
		const FString newDefinitionKey = Pin->GetDefaultAsString().TrimQuotes();
		if (CachedDefinitionKey == newDefinitionKey)
			return;

		CachedDefinitionKey = newDefinitionKey;
		RefreshGeneratedPins();
	}
}

void UK2Node_BreakJsonObjectByDefinition::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* schema = CompilerContext.GetSchema();
	if (!schema)
	{
		BreakAllNodeLinks();
		return;
	}

	const FString definitionKey = GetSelectedDefinitionKey();
	if (definitionKey.IsEmpty() || definitionKey.Equals(TEXT("none"), ESearchCase::IgnoreCase))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("NoDefinitionSelected", "@@ must have a valid JSON definition selected.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	FMounteaJsonObjectDefinition definition;
	TArray<FString> errors;
	if (!ResolveSelectedDefinition(definition, errors))
	{
		const FString errorText = errors.Num() > 0 ? FString::Join(errors, TEXT("\n")) : FString::Printf(TEXT("Could not resolve JSON definition '%s'."), *definitionKey);
		CompilerContext.MessageLog.Error(*FString::Printf(TEXT("@@ %s"), *errorText), this);
		BreakAllNodeLinks();
		return;
	}

	UFunction* validateFunction = UMounteaAdvancedInventoryJsonStatics::StaticClass()->FindFunctionByName(
		GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, ValidateJsonObjectAgainstDefinitionKey));

	if (!validateFunction)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingRuntimeFunctions", "@@ could not find required JSON runtime functions.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* execPin = GetExecPin();
	UEdGraphPin* thenPin = FindPinChecked(UEdGraphSchema_K2::PN_Then, EGPD_Output);
	UEdGraphPin* failedPin = FindPinChecked(FailedPinName, EGPD_Output);
	UEdGraphPin* jsonObjectPin = FindPinChecked(JsonObjectPinName, EGPD_Input);
	UEdGraphPin* errorsPin = FindPinChecked(ErrorsPinName, EGPD_Output);

	UK2Node_CallFunction* validateNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	validateNode->SetFromFunction(validateFunction);
	validateNode->AllocateDefaultPins();

	CopyPinLinksAndDefaults(CompilerContext, jsonObjectPin, validateNode->FindPinChecked(TEXT("Target")));
	validateNode->FindPinChecked(DefinitionKeyPinName)->DefaultValue = definitionKey;
	CompilerContext.MovePinLinksToIntermediate(*errorsPin, *validateNode->FindPinChecked(ErrorsPinName));

	UK2Node_IfThenElse* validationBranchNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
	validationBranchNode->AllocateDefaultPins();
	CompilerContext.MovePinLinksToIntermediate(*execPin, *validationBranchNode->GetExecPin());
	schema->TryCreateConnection(validateNode->GetReturnValuePin(), validationBranchNode->GetConditionPin());

	UEdGraphPin* currentExecPin = validationBranchNode->GetThenPin();
	UEdGraphPin* firstFailurePin = validationBranchNode->GetElsePin();
	CompilerContext.MovePinLinksToIntermediate(*failedPin, *firstFailurePin);

	auto connectToFailure = [schema, firstFailurePin](UEdGraphPin* FailureExecPin)
	{
		if (!FailureExecPin || FailureExecPin == firstFailurePin)
			return;

		for (UEdGraphPin* linkedPin : firstFailurePin->LinkedTo)
		{
			if (linkedPin)
				schema->TryCreateConnection(FailureExecPin, linkedPin);
		}
	};

	for (const FMounteaJsonObjectDefinitionField& field : definition.Fields)
	{
		if (field.FieldName.IsNone())
			continue;

		UEdGraphPin* targetFieldPin = FindPin(GetFieldPinName(field.FieldName), EGPD_Output);
		if (!targetFieldPin || targetFieldPin->LinkedTo.Num() == 0)
			continue;

		UFunction* getterFunction = GetGetterFunctionForPinType(field.FieldValueType);
		if (!getterFunction)
		{
			CompilerContext.MessageLog.Error(*FString::Printf(TEXT("@@ has unsupported JSON definition field '%s'."), *field.FieldName.ToString()), this);
			BreakAllNodeLinks();
			return;
		}

		UK2Node_CallFunction* getterNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		getterNode->SetFromFunction(getterFunction);
		getterNode->AllocateDefaultPins();

		schema->TryCreateConnection(currentExecPin, getterNode->GetExecPin());
		CopyPinLinksAndDefaults(CompilerContext, jsonObjectPin, getterNode->FindPinChecked(TEXT("Target")));
		getterNode->FindPinChecked(TEXT("FieldName"))->DefaultValue = field.FieldName.ToString();

		UEdGraphPin* getterValuePin = getterNode->FindPinChecked(TEXT("Value"));
		getterValuePin->PinType = targetFieldPin->PinType;
		CompilerContext.MovePinLinksToIntermediate(*targetFieldPin, *getterValuePin);

		if (field.bRequired)
		{
			UK2Node_IfThenElse* getterBranchNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
			getterBranchNode->AllocateDefaultPins();
			schema->TryCreateConnection(getterNode->GetThenPin(), getterBranchNode->GetExecPin());
			schema->TryCreateConnection(getterNode->GetReturnValuePin(), getterBranchNode->GetConditionPin());
			connectToFailure(getterBranchNode->GetElsePin());
			currentExecPin = getterBranchNode->GetThenPin();
		}
		else
		{
			currentExecPin = getterNode->GetThenPin();
		}
	}

	CompilerContext.MovePinLinksToIntermediate(*thenPin, *currentExecPin);

	BreakAllNodeLinks();
}

void UK2Node_BreakJsonObjectByDefinition::PostReconstructNode()
{
	Super::PostReconstructNode();

	const UEdGraphSchema_K2* schema = GetDefault<UEdGraphSchema_K2>();
	if (!schema)
		return;

	for (UEdGraphPin* pin : Pins)
	{
		if (!IsGeneratedFieldPin(pin))
			continue;

		TArray<UEdGraphPin*> linkedPins = pin->LinkedTo;
		for (UEdGraphPin* linkedPin : linkedPins)
		{
			if (linkedPin && !schema->ArePinTypesCompatible(pin->PinType, linkedPin->PinType))
				pin->BreakLinkTo(linkedPin);
		}
	}
}

bool UK2Node_BreakJsonObjectByDefinition::ShouldUseJsonDefinitionSelector(UEdGraphPin* Pin) const
{
	return Pin
		&& Pin->Direction == EGPD_Input
		&& Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_String
		&& Pin->PinName == DefinitionKeyPinName;
}

void UK2Node_BreakJsonObjectByDefinition::RefreshGeneratedPins()
{
	if (bIsRefreshingGeneratedPins)
		return;

	TGuardValue<bool> refreshGuard(bIsRefreshingGeneratedPins, true);
	ReconstructNode();
	if (UEdGraph* graph = GetGraph())
		graph->NotifyGraphChanged();
}

FString UK2Node_BreakJsonObjectByDefinition::GetSelectedDefinitionKey() const
{
	const UEdGraphPin* definitionKeyPin = FindPin(DefinitionKeyPinName, EGPD_Input);
	if (definitionKeyPin)
	{
		const FString pinValue = definitionKeyPin->GetDefaultAsString().TrimQuotes();
		return pinValue.IsEmpty() ? CachedDefinitionKey : pinValue;
	}

	return CachedDefinitionKey;
}

bool UK2Node_BreakJsonObjectByDefinition::ResolveSelectedDefinition(FMounteaJsonObjectDefinition& OutDefinition, TArray<FString>& Errors) const
{
	const FString definitionKey = GetSelectedDefinitionKey();
	if (definitionKey.IsEmpty() || definitionKey.Equals(TEXT("none"), ESearchCase::IgnoreCase))
	{
		OutDefinition = FMounteaJsonObjectDefinition();
		Errors.Reset();
		return false;
	}

	return UMounteaAdvancedInventoryJsonStatics::ResolveJsonObjectDefinitionByKey(definitionKey, OutDefinition, Errors);
}

void UK2Node_BreakJsonObjectByDefinition::CreateFieldPins(const FMounteaJsonObjectDefinition& Definition)
{
	for (const FMounteaJsonObjectDefinitionField& field : Definition.Fields)
	{
		if (field.FieldName.IsNone())
			continue;

		FEdGraphPinType pinType = field.FieldValueType;
		pinType.ContainerType = EPinContainerType::None;
		if (!IsSupportedFieldPinType(pinType))
			continue;

		UEdGraphPin* fieldPin = CreatePin(EGPD_Output, pinType, GetFieldPinName(field.FieldName));
		fieldPin->PinFriendlyName = FText::FromName(field.FieldName);
		fieldPin->PinToolTip = FText::Format(LOCTEXT("GeneratedFieldTooltip", "JSON field: {0}"), FText::FromName(field.FieldName)).ToString();
	}
}

bool UK2Node_BreakJsonObjectByDefinition::IsSupportedFieldPinType(const FEdGraphPinType& PinType)
{
	if (PinType.ContainerType != EPinContainerType::None)
		return false;

	return PinType.PinCategory == UEdGraphSchema_K2::PC_Int ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Int64 ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Real ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Boolean ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_String ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Name ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Byte ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Text ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Struct ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Object ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_SoftObject ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Class ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_SoftClass;
}

UFunction* UK2Node_BreakJsonObjectByDefinition::GetGetterFunctionForPinType(const FEdGraphPinType& PinType)
{
	const UClass* staticsClass = UMounteaAdvancedInventoryJsonStatics::StaticClass();

	if (!IsSupportedFieldPinType(PinType))
		return nullptr;

	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Int)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetIntJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Int64)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetInt64JsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Real)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetFloatJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Boolean)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetBoolJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_String)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetStringJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Name)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetNameJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Byte)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetByteJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Text)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetTextJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Object)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetObjectJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_SoftObject)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetSoftObjectJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Class)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetClassJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_SoftClass)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetSoftClassJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Struct)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, GetStructJsonField));

	return nullptr;
}

FName UK2Node_BreakJsonObjectByDefinition::GetFieldPinName(const FName FieldName)
{
	return FName(*(FieldPinPrefix + FieldName.ToString()));
}

bool UK2Node_BreakJsonObjectByDefinition::IsGeneratedFieldPin(const UEdGraphPin* Pin)
{
	return Pin && Pin->Direction == EGPD_Output && Pin->PinName.ToString().StartsWith(FieldPinPrefix);
}

void UK2Node_BreakJsonObjectByDefinition::CopyPinDefaults(const UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
{
	if (!SourcePin || !TargetPin)
		return;

	TargetPin->DefaultValue = SourcePin->DefaultValue;
	TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
	TargetPin->DefaultObject = SourcePin->DefaultObject;
	TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
}

void UK2Node_BreakJsonObjectByDefinition::CopyPinLinksAndDefaults(FKismetCompilerContext& CompilerContext, UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
{
	if (!SourcePin || !TargetPin)
		return;

	CompilerContext.CopyPinLinksToIntermediate(*SourcePin, *TargetPin);
	CopyPinDefaults(SourcePin, TargetPin);
}

#if WITH_EDITOR

FText UK2Node_BreakJsonObjectByDefinition::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	FText functionName = LOCTEXT("BreakJsonObjectByDefinition_Title", "JSON - Break Object By Definition");

	if (TitleType == ENodeTitleType::FullTitle)
	{
		FText contextString = LOCTEXT("BreakJsonObjectByDefinition_Subtitle", "Source is Mountea Json Definition");

		FFormatNamedArguments namedArgs;
		namedArgs.Add(TEXT("FunctionName"), functionName);
		namedArgs.Add(TEXT("ContextString"), contextString);

		return FText::Format(LOCTEXT("BreakJsonObjectByDefinition_Title_WithContext", "{FunctionName}\n{ContextString}"), namedArgs);
	}

	return functionName;
}

FText UK2Node_BreakJsonObjectByDefinition::GetTooltipText() const
{
	return LOCTEXT("BreakJsonObjectByDefinition_Tooltip",
		"Validates and breaks a Mountea Json Object using a Global Config JSON definition. "
		"Output pins are generated from the merged definition, including included definitions.");
}

FText UK2Node_BreakJsonObjectByDefinition::GetToolTipHeading() const
{
	return LOCTEXT("BreakJsonObjectByDefinition_TooltipHeading", "Mountea Advanced Inventory & Equipment Function");
}

FLinearColor UK2Node_BreakJsonObjectByDefinition::GetNodeTitleColor() const
{
	return FLinearColor(0.0f, 0.55f, 0.62f);
}

FSlateIcon UK2Node_BreakJsonObjectByDefinition::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = FLinearColor(.823f, .823f, .823f);
	return FSlateIcon(FMounteaAdvancedInventoryDeveloperStyle::GetAppStyleSetName(), "MAISStyleSet.K2Node_SetPropertyByName.Small");
}

FName UK2Node_BreakJsonObjectByDefinition::GetCornerIcon() const
{
	const FName superName = Super::GetCornerIcon();
	return superName == NAME_None ? TEXT("MAISStyleSet.MounteaLogo") : superName;
}

FText UK2Node_BreakJsonObjectByDefinition::GetMenuCategory() const
{
	return LOCTEXT("BreakJsonObjectByDefinition_Category", "Mountea|Inventory & Equipment|JSON");
}

#endif

#undef LOCTEXT_NAMESPACE
