// Copyright (C) 2025 Dominik (Pavlicek) Morse. All rights reserved.
//
// Developed for the Mountea Framework as a free tool. This solution is provided
// for use and sharing without charge. Redistribution is allowed under the following conditions:
//
// - You may use this solution in commercial products, provided the product is not
//   this solution itself (or unless significant modifications have been made to the solution).
// - You may not resell or redistribute the original, unmodified solution.
//
// For more information, visit: https://mountea.tools

#include "K2Nodes/K2Node_ConstructJsonObjectFromDefinition.h"

#include "BlueprintActionDatabaseRegistrar.h"
#include "BlueprintNodeSpawner.h"
#include "EdGraphSchema_K2.h"
#include "Helpers/MounteaJsonObject.h"
#include "K2Node_CallFunction.h"
#include "K2Node_IfThenElse.h"
#include "KismetCompiler.h"
#include "Settings/MounteaAdvancedInventoryGlobalConfig.h"
#include "Statics/MounteaAdvancedInventoryJsonStatics.h"
#include "Styling/MounteaAdvancedInventoryDeveloperStyle.h"

#define LOCTEXT_NAMESPACE "K2Node_ConstructJsonObjectFromDefinition"

const FName UK2Node_ConstructJsonObjectFromDefinition::TargetPinName(TEXT("Target"));
const FName UK2Node_ConstructJsonObjectFromDefinition::DefinitionKeyPinName(TEXT("DefinitionKey"));
const FName UK2Node_ConstructJsonObjectFromDefinition::JsonObjectPinName(TEXT("JsonObject"));
const FName UK2Node_ConstructJsonObjectFromDefinition::FailedPinName(TEXT("Failed"));
const FString UK2Node_ConstructJsonObjectFromDefinition::FieldPinPrefix(TEXT("Field_"));

UK2Node_ConstructJsonObjectFromDefinition::UK2Node_ConstructJsonObjectFromDefinition(const FObjectInitializer& ObjectInitializer)
	: Super(ObjectInitializer)
{
	bDisableOrphanPinSaving = true;
}

void UK2Node_ConstructJsonObjectFromDefinition::AllocateDefaultPins()
{
	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Execute);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, UEdGraphSchema_K2::PN_Then);
	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Exec, FailedPinName);

	CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_Object, UObject::StaticClass(), TargetPinName);

	UEdGraphPin* definitionKeyPin = CreatePin(EGPD_Input, UEdGraphSchema_K2::PC_String, DefinitionKeyPinName);
	definitionKeyPin->DefaultValue = CachedDefinitionKey.IsEmpty() ? TEXT("none") : CachedDefinitionKey;
	definitionKeyPin->AutogeneratedDefaultValue = TEXT("none");

	CreateFieldPins();

	CreatePin(EGPD_Output, UEdGraphSchema_K2::PC_Object, UMounteaJsonObject::StaticClass(), JsonObjectPinName);
}

void UK2Node_ConstructJsonObjectFromDefinition::GetMenuActions(FBlueprintActionDatabaseRegistrar& ActionRegistrar) const
{
	UClass* actionKey = GetClass();
	if (ActionRegistrar.IsOpenForRegistration(actionKey))
	{
		UBlueprintNodeSpawner* nodeSpawner = UBlueprintNodeSpawner::Create(GetClass());
		check(nodeSpawner != nullptr);
		ActionRegistrar.AddBlueprintAction(actionKey, nodeSpawner);
	}
}

bool UK2Node_ConstructJsonObjectFromDefinition::IsConnectionDisallowed(const UEdGraphPin* MyPin, const UEdGraphPin* OtherPin, FString& OutReason) const
{
	if (MyPin && MyPin->PinName == DefinitionKeyPinName)
	{
		OutReason = LOCTEXT("DefinitionKeyMustBeLiteral", "Definition Key must be selected from the node dropdown so field pins can be generated.").ToString();
		return true;
	}

	return false;
}

void UK2Node_ConstructJsonObjectFromDefinition::PinDefaultValueChanged(UEdGraphPin* Pin)
{
	Super::PinDefaultValueChanged(Pin);

	if (Pin && Pin->PinName == DefinitionKeyPinName)
	{
		const FString newDefinitionKey = Pin->GetDefaultAsString().TrimQuotes();
		if (CachedDefinitionKey == newDefinitionKey)
			return;

		CachedDefinitionKey = newDefinitionKey;
		RefreshGeneratedPins();
	}
}

void UK2Node_ConstructJsonObjectFromDefinition::ExpandNode(FKismetCompilerContext& CompilerContext, UEdGraph* SourceGraph)
{
	Super::ExpandNode(CompilerContext, SourceGraph);

	const UEdGraphSchema_K2* schema = CompilerContext.GetSchema();
	if (!schema)
	{
		BreakAllNodeLinks();
		return;
	}

	const FString definitionKey = GetSelectedDefinitionKey();
	if (definitionKey.IsEmpty() || definitionKey.Equals(TEXT("none"), ESearchCase::IgnoreCase))
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("NoDefinitionSelected", "@@ must have a valid JSON definition selected.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	FMounteaJsonObjectDefinition definition;
	TArray<FString> errors;
	if (!ResolveSelectedDefinition(definition, errors))
	{
		const FString errorText = errors.Num() > 0 ? FString::Join(errors, TEXT("\n")) : FString::Printf(TEXT("Could not resolve JSON definition '%s'."), *definitionKey);
		CompilerContext.MessageLog.Error(*FString::Printf(TEXT("@@ %s"), *errorText), this);
		BreakAllNodeLinks();
		return;
	}

	UFunction* createFunction = UMounteaAdvancedInventoryJsonStatics::StaticClass()->FindFunctionByName(
		GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, CreateJsonObjectFromDefinitionKey));
	UFunction* isValidFunction = UMounteaAdvancedInventoryJsonStatics::StaticClass()->FindFunctionByName(
		GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, IsValidJsonObject));

	if (!createFunction || !isValidFunction)
	{
		CompilerContext.MessageLog.Error(*LOCTEXT("MissingRuntimeFunctions", "@@ could not find required JSON runtime functions.").ToString(), this);
		BreakAllNodeLinks();
		return;
	}

	UEdGraphPin* execPin = GetExecPin();
	UEdGraphPin* thenPin = FindPinChecked(UEdGraphSchema_K2::PN_Then, EGPD_Output);
	UEdGraphPin* failedPin = FindPinChecked(FailedPinName, EGPD_Output);
	UEdGraphPin* targetPin = FindPinChecked(TargetPinName, EGPD_Input);
	UEdGraphPin* jsonObjectPin = FindPinChecked(JsonObjectPinName, EGPD_Output);

	UK2Node_CallFunction* createNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	createNode->SetFromFunction(createFunction);
	createNode->AllocateDefaultPins();

	CompilerContext.MovePinLinksToIntermediate(*execPin, *createNode->GetExecPin());
	CompilerContext.MovePinLinksToIntermediate(*targetPin, *createNode->FindPinChecked(TEXT("Target")));
	createNode->FindPinChecked(DefinitionKeyPinName)->DefaultValue = definitionKey;

	UK2Node_CallFunction* isValidNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
	isValidNode->SetFromFunction(isValidFunction);
	isValidNode->AllocateDefaultPins();

	UEdGraphPin* createReturnPin = createNode->GetReturnValuePin();
	schema->TryCreateConnection(createReturnPin, isValidNode->FindPinChecked(TEXT("Target")));

	UK2Node_IfThenElse* initialBranchNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
	initialBranchNode->AllocateDefaultPins();
	schema->TryCreateConnection(createNode->GetThenPin(), initialBranchNode->GetExecPin());
	schema->TryCreateConnection(isValidNode->GetReturnValuePin(), initialBranchNode->GetConditionPin());

	UEdGraphPin* currentExecPin = initialBranchNode->GetThenPin();
	UEdGraphPin* currentJsonPin = createReturnPin;
	UEdGraphPin* firstFailurePin = initialBranchNode->GetElsePin();
	CompilerContext.MovePinLinksToIntermediate(*failedPin, *firstFailurePin);

	auto connectToFailure = [schema, firstFailurePin](UEdGraphPin* FailureExecPin)
	{
		if (!FailureExecPin || FailureExecPin == firstFailurePin)
			return;

		for (UEdGraphPin* linkedPin : firstFailurePin->LinkedTo)
		{
			if (linkedPin)
				schema->TryCreateConnection(FailureExecPin, linkedPin);
		}
	};

	for (const FMounteaJsonObjectDefinitionField& field : definition.Fields)
	{
		if (field.FieldName.IsNone())
			continue;

		UEdGraphPin* sourceFieldPin = FindPin(GetFieldPinName(field.FieldName), EGPD_Input);
		if (!sourceFieldPin || ShouldSkipUnconnectedFieldPin(sourceFieldPin))
			continue;

		UFunction* setterFunction = GetSetterFunctionForPinType(field.FieldValueType);
		if (!setterFunction)
		{
			CompilerContext.MessageLog.Error(*FString::Printf(TEXT("@@ has unsupported JSON definition field '%s'."), *field.FieldName.ToString()), this);
			BreakAllNodeLinks();
			return;
		}

		UK2Node_CallFunction* setterNode = CompilerContext.SpawnIntermediateNode<UK2Node_CallFunction>(this, SourceGraph);
		setterNode->SetFromFunction(setterFunction);
		setterNode->AllocateDefaultPins();

		schema->TryCreateConnection(currentExecPin, setterNode->GetExecPin());
		schema->TryCreateConnection(currentJsonPin, setterNode->FindPinChecked(TEXT("Target")));
		setterNode->FindPinChecked(TEXT("FieldName"))->DefaultValue = field.FieldName.ToString();

		UEdGraphPin* setterValuePin = setterNode->FindPinChecked(TEXT("Value"));
		if (field.FieldValueType.PinCategory == UEdGraphSchema_K2::PC_Struct)
			setterValuePin->PinType = field.FieldValueType;

		if (sourceFieldPin->LinkedTo.Num() > 0)
			CompilerContext.MovePinLinksToIntermediate(*sourceFieldPin, *setterValuePin);
		else
			CopyPinDefaults(sourceFieldPin, setterValuePin);

		UK2Node_IfThenElse* setterBranchNode = CompilerContext.SpawnIntermediateNode<UK2Node_IfThenElse>(this, SourceGraph);
		setterBranchNode->AllocateDefaultPins();
		schema->TryCreateConnection(setterNode->GetThenPin(), setterBranchNode->GetExecPin());
		schema->TryCreateConnection(setterNode->GetReturnValuePin(), setterBranchNode->GetConditionPin());
		connectToFailure(setterBranchNode->GetElsePin());

		currentExecPin = setterBranchNode->GetThenPin();
		currentJsonPin = setterNode->FindPinChecked(JsonObjectPinName);
	}

	CompilerContext.MovePinLinksToIntermediate(*thenPin, *currentExecPin);
	CompilerContext.MovePinLinksToIntermediate(*jsonObjectPin, *currentJsonPin);

	BreakAllNodeLinks();
}

void UK2Node_ConstructJsonObjectFromDefinition::PostReconstructNode()
{
	Super::PostReconstructNode();

	const UEdGraphSchema_K2* schema = GetDefault<UEdGraphSchema_K2>();
	if (!schema)
		return;

	for (UEdGraphPin* pin : Pins)
	{
		if (!IsGeneratedFieldPin(pin))
			continue;

		TArray<UEdGraphPin*> linkedPins = pin->LinkedTo;
		for (UEdGraphPin* linkedPin : linkedPins)
		{
			if (linkedPin && !schema->ArePinTypesCompatible(pin->PinType, linkedPin->PinType))
				pin->BreakLinkTo(linkedPin);
		}
	}
}

bool UK2Node_ConstructJsonObjectFromDefinition::ShouldUseJsonDefinitionSelector(UEdGraphPin* Pin) const
{
	return Pin
		&& Pin->Direction == EGPD_Input
		&& Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_String
		&& Pin->PinName == DefinitionKeyPinName;
}

void UK2Node_ConstructJsonObjectFromDefinition::RefreshGeneratedPins()
{
	if (bIsRefreshingGeneratedPins)
		return;

	TGuardValue<bool> refreshGuard(bIsRefreshingGeneratedPins, true);
	ReconstructNode();
	if (UEdGraph* graph = GetGraph())
		graph->NotifyGraphChanged();
}

FString UK2Node_ConstructJsonObjectFromDefinition::GetSelectedDefinitionKey() const
{
	const UEdGraphPin* definitionKeyPin = FindPin(DefinitionKeyPinName, EGPD_Input);
	if (definitionKeyPin)
	{
		const FString pinValue = definitionKeyPin->GetDefaultAsString().TrimQuotes();
		return pinValue.IsEmpty() ? CachedDefinitionKey : pinValue;
	}

	return CachedDefinitionKey;
}

FString UK2Node_ConstructJsonObjectFromDefinition::BuildDefinitionIssueText() const
{
	return UMounteaAdvancedInventoryJsonStatics::BuildJsonDefinitionIssueText(GetSelectedDefinitionKey());
}

bool UK2Node_ConstructJsonObjectFromDefinition::ResolveSelectedDefinition(FMounteaJsonObjectDefinition& OutDefinition, TArray<FString>& Errors) const
{
	const FString definitionKey = GetSelectedDefinitionKey();
	if (definitionKey.IsEmpty() || definitionKey.Equals(TEXT("none"), ESearchCase::IgnoreCase))
	{
		OutDefinition = FMounteaJsonObjectDefinition();
		Errors.Reset();
		return false;
	}

	return UMounteaAdvancedInventoryJsonStatics::ResolveJsonObjectDefinitionByKey(definitionKey, OutDefinition, Errors);
}

void UK2Node_ConstructJsonObjectFromDefinition::CreateFieldPins()
{
	TArray<FMounteaResolvedJsonObjectDefinitionField> resolvedFields;
	TArray<FString> errors;
	if (!UMounteaAdvancedInventoryJsonStatics::ResolveJsonObjectDefinitionFieldsByKey(GetSelectedDefinitionKey(), resolvedFields, errors))
		return;

	TSet<FName> usedPinNames;
	for (const FMounteaResolvedJsonObjectDefinitionField& fieldPinData : resolvedFields)
	{
		const FMounteaJsonObjectDefinitionField& field = fieldPinData.Field;
		if (field.FieldName.IsNone())
			continue;

		FEdGraphPinType pinType = field.FieldValueType;
		pinType.ContainerType = EPinContainerType::None;
		if (!IsSupportedFieldPinType(pinType))
			continue;

		UEdGraphPin* fieldPin = CreatePin(EGPD_Input, pinType, UMounteaAdvancedInventoryJsonStatics::MakeJsonDefinitionFieldPinName(FieldPinPrefix, field.FieldName, fieldPinData.OccurrenceIndex, usedPinNames));
		fieldPin->PinFriendlyName = FText::FromName(field.FieldName);
		fieldPin->PinToolTip = UMounteaAdvancedInventoryJsonStatics::BuildJsonDefinitionFieldPinTooltip(fieldPinData);
		GetDefault<UEdGraphSchema_K2>()->SetPinAutogeneratedDefaultValueBasedOnType(fieldPin);
	}
}

bool UK2Node_ConstructJsonObjectFromDefinition::IsSupportedFieldPinType(const FEdGraphPinType& PinType)
{
	if (PinType.ContainerType != EPinContainerType::None)
		return false;

	return PinType.PinCategory == UEdGraphSchema_K2::PC_Int ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Int64 ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Real ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Boolean ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_String ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Name ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Byte ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Text ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Struct ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Object ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_SoftObject ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_Class ||
		PinType.PinCategory == UEdGraphSchema_K2::PC_SoftClass;
}

UFunction* UK2Node_ConstructJsonObjectFromDefinition::GetSetterFunctionForPinType(const FEdGraphPinType& PinType)
{
	const UClass* staticsClass = UMounteaAdvancedInventoryJsonStatics::StaticClass();

	if (!IsSupportedFieldPinType(PinType))
		return nullptr;

	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Int)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetIntJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Int64)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetInt64JsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Real)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetFloatJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Boolean)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetBoolJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_String)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetStringJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Name)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetNameJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Byte)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetByteJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Text)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetTextJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Object)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetObjectJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_SoftObject)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetSoftObjectJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Class)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetClassJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_SoftClass)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetSoftClassJsonField));
	if (PinType.PinCategory == UEdGraphSchema_K2::PC_Struct)
		return staticsClass->FindFunctionByName(GET_FUNCTION_NAME_CHECKED(UMounteaAdvancedInventoryJsonStatics, SetStructJsonField));

	return nullptr;
}

FName UK2Node_ConstructJsonObjectFromDefinition::GetFieldPinName(const FName FieldName)
{
	return FName(*(FieldPinPrefix + FieldName.ToString()));
}

FName UK2Node_ConstructJsonObjectFromDefinition::GetFieldNameFromPinName(const FName PinName)
{
	FString pinNameString = PinName.ToString();
	if (pinNameString.RemoveFromStart(FieldPinPrefix))
		return FName(*pinNameString);

	return NAME_None;
}

bool UK2Node_ConstructJsonObjectFromDefinition::IsGeneratedFieldPin(const UEdGraphPin* Pin)
{
	return Pin && Pin->Direction == EGPD_Input && Pin->PinName.ToString().StartsWith(FieldPinPrefix);
}

bool UK2Node_ConstructJsonObjectFromDefinition::ShouldSkipUnconnectedFieldPin(const UEdGraphPin* Pin)
{
	return Pin
		&& Pin->LinkedTo.Num() == 0
		&& Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Object
		&& Pin->DefaultObject == nullptr;
}

void UK2Node_ConstructJsonObjectFromDefinition::CopyPinDefaults(const UEdGraphPin* SourcePin, UEdGraphPin* TargetPin)
{
	if (!SourcePin || !TargetPin)
		return;

	TargetPin->DefaultValue = SourcePin->DefaultValue;
	TargetPin->AutogeneratedDefaultValue = SourcePin->AutogeneratedDefaultValue;
	TargetPin->DefaultObject = SourcePin->DefaultObject;
	TargetPin->DefaultTextValue = SourcePin->DefaultTextValue;
}

#if WITH_EDITOR

FText UK2Node_ConstructJsonObjectFromDefinition::GetNodeTitle(ENodeTitleType::Type TitleType) const
{
	FText functionName = LOCTEXT("ConstructJsonObjectFromDefinition_Title", "JSON - Construct Object From Definition");

	if (TitleType == ENodeTitleType::FullTitle)
	{
		FText contextString = LOCTEXT("ConstructJsonObjectFromDefinition_Subtitle", "Source is Mountea Json Definition");

		FFormatNamedArguments namedArgs;
		namedArgs.Add(TEXT("FunctionName"), functionName);
		namedArgs.Add(TEXT("ContextString"), contextString);

		return FText::Format(LOCTEXT("ConstructJsonObjectFromDefinition_Title_WithContext", "{FunctionName}\n{ContextString}"), namedArgs);
	}

	return functionName;
}

FText UK2Node_ConstructJsonObjectFromDefinition::GetTooltipText() const
{
	return LOCTEXT("ConstructJsonObjectFromDefinition_Tooltip",
		"Constructs a Mountea Json Object from a Global Config JSON definition. "
		"Input pins are generated from the merged definition, including included definitions.");
}

FText UK2Node_ConstructJsonObjectFromDefinition::GetVisualWarningTooltipText() const
{
	return FText::FromString(BuildDefinitionIssueText());
}

FText UK2Node_ConstructJsonObjectFromDefinition::GetToolTipHeading() const
{
	return LOCTEXT("ConstructJsonObjectFromDefinition_TooltipHeading", "Mountea Advanced Inventory & Equipment Function");
}

FLinearColor UK2Node_ConstructJsonObjectFromDefinition::GetNodeTitleColor() const
{
	return FLinearColor(0.0f, 0.55f, 0.62f);
}

FSlateIcon UK2Node_ConstructJsonObjectFromDefinition::GetIconAndTint(FLinearColor& OutColor) const
{
	OutColor = FLinearColor(.823f, .823f, .823f);
	return FSlateIcon(FMounteaAdvancedInventoryDeveloperStyle::GetAppStyleSetName(), "MAISStyleSet.K2Node_SetPropertyByName.Small");
}

FName UK2Node_ConstructJsonObjectFromDefinition::GetCornerIcon() const
{
	const FName superName = Super::GetCornerIcon();
	return superName == NAME_None ? TEXT("MAISStyleSet.MounteaLogo") : superName;
}

bool UK2Node_ConstructJsonObjectFromDefinition::ShowVisualWarning() const
{
	return !BuildDefinitionIssueText().IsEmpty();
}

FText UK2Node_ConstructJsonObjectFromDefinition::GetMenuCategory() const
{
	return LOCTEXT("ConstructJsonObjectFromDefinition_Category", "Mountea|Inventory & Equipment|JSON");
}

#endif

#undef LOCTEXT_NAMESPACE
